services:

    #
    # Form Types
    #
    admin.user.form_type.admin_user:
        class: %admin.user.form_type.admin_user.class%
        arguments:
            admin_user_factory: @elcodi.factory.admin_user
        tags:
            - { name: form.type, alias: admin_user_form_type_admin_user }
