security:
    access_control:
            # Admin area
            login_area:
                path: ^/gestor/login.*
                roles: IS_AUTHENTICATED_ANONYMOUSLY

            password_area:
                path: ^/gestor/password.*
                roles: IS_AUTHENTICATED_ANONYMOUSLY

            admin_area:
                path: ^/gestor/
                roles: ROLE_ADMIN

            # Customer area
            customer_login_area:
                path: ^/(cliente|customer|client)/(login|nuevo|new|nouveau|recordar-contrasena|password-remember|rappeler-mot-de-passe|recordatorio-enviado|recover-sent|recuperer-envoye|recuperar-contrasena|recover-password|recuperer-mot-de-passe).*
                roles: IS_AUTHENTICATED_ANONYMOUSLY

            customer_area:
                path: /(cliente|customer|client)/.*
                roles: ROLE_CUSTOMER

            checkout_area:
                path: /(procesar|checkout|acheter)/.*
                roles: ROLE_CUSTOMER
