imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            excluded_404:
                 - ^/
            handler:      grouped
        grouped:
            type:         group
            members:      [streamed, swift]
        streamed:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        swift:
            type:         swift_mailer
            from_email:   me@example.com
            to_email:     me@example.com
            subject:      "[WEBSITE] Error"
            level:        debug
        login:
            type:         stream
            path:         "%kernel.logs_dir%/auth.log"
            level:        info
            channels:     security
