imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @StoreBundle/Resources/config/translations.yml }
#    - { resource: @StoreBundle/Resources/config/mapping.yml }
    - { resource: @StoreBundle/Resources/config/filesystem.yml }
    - { resource: @StoreBundle/Resources/config/cache.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    bundles:
        - AdminCoreBundle
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

doctrine_cache:
   providers:
      elcodi:
         type: array

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool:     { type: file }

be_simple_i18n_routing: ~

doctrine_cache:
    providers:
        elcodi:
            type: redis
        elcodi_configuration:
            type: redis

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:   ~
        sonata.block.service.action: ~
        sonata.block.service.rss:    ~

sonata_admin:
    title: Gestor
    title_logo: /bundles/admincore/img/logo.png
#    title_logo_mini: /bundles/admincore/img/logo.png
    templates:
        layout:  AdminCoreBundle::standard_layout.html.twig

sensio_framework_extra:
    request:
        converters: false

controller_extra:
    factory:
        default_method: create
        default_static: false
