security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_area:
            pattern: ^/gestor/login$
            anonymous: ~

        password_area:
            pattern: ^/password.*$
            anonymous: ~

        admin_secured_area:
            context: secure_area
            provider: adminuser
            pattern: ^/gestor/?.*$

            form_login:
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: admin_user_form_type_login[username]
                password_parameter: admin_user_form_type_login[password]
            logout:
                path:   admin_logout
                target: admin_homepage
                invalidate_session: false

        customer_secured_area:
            pattern: ^/
            context: customer_secured_area
            provider: customer
            anonymous: true
            security: true
            form_login:
                login_path: store_login
                check_path: store_login_check
                username_parameter: store_user_form_type_login[email]
                password_parameter: store_user_form_type_login[password]
            logout:
                path:   store_logout
                target: store_homepage
                invalidate_session: false
