fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#
# Imported routes from admin
#
admin_core:
    resource: "@AdminCoreBundle/Resources/config/routing.yml"
    prefix: /gestor

admin_routes:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix: /gestor

admin_login_check:
    path:  /gestor/login_check

admin_logout:
    path: /gestor/logout