imports:
    - { resource: @ElcodiUserBundle/Resources/security/encoders.yml }
    - { resource: @ElcodiUserBundle/Resources/security/providers.yml }
    - { resource: @AdminUserBundle/Resources/security/firewalls.yml }
    - { resource: @AdminUserBundle/Resources/security/accessControl.yml }
    - { resource: @AdminUserBundle/Resources/security/roles.yml }