parameters:

    #
    # Form Types
    #
    admin.core.form_type.login.class: QBH\AdminCoreBundle\Form\Type\LoginType

    #
    # Twig extensions
    #
    admin.core.twig.admin_core_extension.class: QBH\AdminCoreBundle\Twig\AdminCoreExtension