services:

    #
    # Form Types
    #
    admin.user.form_type.login:
        class: QBH\AdminCoreBundle\Form\Type\LoginType
        arguments:
            router: @router
        tags:
            - { name: form.type, alias: admin_user_form_type_login }