services:

    #
    # Form Types
    #
    qbh.admin.user.form_type.login:
        class: QBH\AdminCoreBundle\Form\Type\LoginType
        arguments:
            router: @router
        tags:
            - { name: form.type, alias: admin_user_form_type_login }

    #
    # Form extensions
    #
    # Admin text type: render help close to the field
    qbh.admin.type_extension.help:
        class: QBH\AdminCoreBundle\Form\Extension\HelpTypeExtension
        tags:
            - { name: form.type_extension, alias: form }