QBH\AdminUserBundle\Entity\AdminUser:
    type: entity
    repositoryClass: QBH\AdminUserBundle\Repository\AdminUserRepository
    table: admin_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]
